name: CI
on: [push, pull_request]
jobs:
  main:
    name: Test with OCaml v${{ matrix.ocaml }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml:
          - 5.1.x
          - 4.14.x
          - 4.10.x
    steps:
      - uses: actions/checkout@v3
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml }}
      - name: Install dependencies
        run: opam install . --deps-only --with-test
      - name: Build
        run: opam exec -- dune build @install
      - name: Test
        run: opam exec -- dune runtest
